name: mad_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  cached_network_image: ^3.3.1
  intl: ^0.19.0
  timeago: ^3.6.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  photo_view: ^0.14.0

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.2.1
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^17.2.3
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logobg.png
    - assets/person.jfif
    - assets/fire.jfif
    - assets/group.jfif
    - assets/google.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/logobg.png
  remove_alpha_ios: true
